### ISSUE TITLE
Don't know how to REQUIRE SB-BSD-SOCKETS.

### ISSUE THREAD

**Issue by masterxor** [slime/slime#162]
System:

**Comment by liamh** [comment]
I found that I could quickload sytems from the shell, but I got this error when loading them in SBCL started from SLIME. It turns out that for SBCL to find sb-bsd-sockets, the environment variable SBCL_HOME needs to be defined as the location of the SBCL source directory. It was defined in my shell, but not in SLIME. This can be fixed by specifying :env in the lisp implementation definition, e.g.

    (setq slime-lisp-implementations
          `((sbcl ("/usr/local/bin/sbcl" "--core" "mycore.core")
    	      :env ("SBCL_HOME=/usr/local/lib/sbcl"))))

I hope this helps others.
