### ISSUE TITLE
swank/sbcl cannot bind socket on Linux with disabled IPv4-mapped IPv6 addresses

### ISSUE THREAD

**Issue by trupanka** [slime/slime#402]
On Linux with disabled ipv4-ipv6 address mapping, sbcl `socket-bind` cannot bind socket

Steps to reproduce:
1. \# sysctl net.ipv6.bindv6only=1
2. C-u M-x slime; sbcl
3. backtrace:
```
0: (SB-BSD-SOCKETS:SOCKET-ERROR "bind" 22)
1: (SB-BSD-SOCKETS::CALL-WITH-SOCKET-ADDR #<SB-BSD-SOCKETS:INET6-SOCKET [::]:0, fd: 4 {1002401E03}> (#(0 0 0 0 0 0 0 0 0 0 255 255 ...) 0) #<CLOSURE (FLET SB-BSD-SOCKETS::WITH-SOCKET-ADDR-THUNK :IN SB-BSD-SOCKETS:SOCKET-BIND) {3FFF6ACF4FB}>)
2: ((:METHOD SB-BSD-SOCKETS:SOCKET-BIND (SB-BSD-SOCKETS:SOCKET)) #<SB-BSD-SOCKETS:INET6-SOCKET [::]:0, fd: 4 {1002401E03}> #(0 0 0 0 0 0 0 0 0 0 255 255 ...) 0) [fast-method]
3: ((FLET SWANK/BACKEND:CREATE-SOCKET :IN "/home/trupanka/.emacs.d/elpa/slime-20170828.451/swank/sbcl.lisp") "127.0.0.1" 0 :BACKLOG NIL)
4: (SWANK::SOCKET-QUEST 0 NIL)
5: (SWANK::SETUP-SERVER 0 #<CLOSURE (LAMBDA (SWANK::PORT) :IN SWANK:START-SERVER) {10020F643B}> :SPAWN NIL NIL)
```

**Comment by luismbo** [comment]
I've tried to reproduce this but `sysctl net.ipv6.bindv6only=1` doesn't seem to have the desired effect on my system. I can still create a bind an IPv4 socket afterwards. Can you help me troubleshoot that?

In any case, does changing `*loopback-interface*` from `"127.0.0.1"` to `"localhost"` in `swank.lisp` help?

**Comment by trupanka** [comment]
Step 1.5.
SBCL_VERSION=1.3.21-linux-x86-64; mv ~/.slime/fasl/2.20/sbcl-"$SBCL_VERSION" ~/.slime/fasl/2.20/sbcl-"$SBCL_VERSION".bak

> In any case, does changing *loopback-interface* from "127.0.0.1" to "localhost" in swank.lisp help?
doesn't help

Maybe I have weirdo network configuration on my machine. But slime runs `clisp`, `ccl`, `ecl` without troubles. Only `sbcl` tries to bind 127.0.0.1 as IPv6.

**Comment by luismbo** [comment]
That was quite an edit. In the initial version of your comment, you mentioned that this only happens with SBCL. That's interesting. (I should try the same version as you: 1.3.21.)

In any case, generally using localhost instead of 127.0.0.1 seems more robust.

@stassats do you see any disadvantages in doing that?

**Comment by luismbo** [comment]
@trupanka do you have a less visually intense name I can credit in an upcoming bugfix commit? 😅

**Comment by trupanka** [comment]
@luismbo Evgeny S.

**Comment by hardenedapple** [comment]
Just mentioning here so that others can easily find it.
On some misconfigured systems this change can lead to slime failing to start with the below for `sbcl`, and probably similar problems with other lisps.

```
debugger invoked on a SB-BSD-SOCKETS:SOCKET-ERROR in thread
#<THREAD "main thread" RUNNING {10019562D3}>:
  Socket error in "bind": 99 (Cannot assign requested address)

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [USE-VALUE] Try a port other than 0
  1: [ABORT    ] Exit debugger, returning to top level.

(SB-BSD-SOCKETS:SOCKET-ERROR "bind" 99)
; File has been modified since compilation:
;   SYS:CONTRIB;SB-BSD-SOCKETS;SOCKETS.LISP.NEWEST
; Using form offset instead of character position.

   source: (ERROR (CONDITION-FOR-ERRNO ERRNO) :ERRNO ERRNO :SYSCALL WHERE)
0]
```

The source of the problem is that on a misconfigured system `gethostbyname("localhost")` can go out to your external nameserver, and that will probably return something other than `127.0.0.1`.

One solution on linux is to ensure that `/etc/hosts` has entries describing `localhost`, I won't vouch for that being the best solution for lack of knowledge.
