### ISSUE TITLE
ABCL fails to load 2.23 with symbol "*STARTED-FROM-EMACS*" is not external

### ISSUE THREAD

**Issue by rladams** [slime/slime#494]
Trying to use ABCL with the SLIME/swank libs from the latest Quicklisp distribution, fails to load with the following error. With v2.20 I'm able to start swank and connect to emacs.

`Armed Bear Common Lisp 1.5.0
Java 1.8.0_181 Oracle Corporation
OpenJDK 64-Bit Server VM
Low-level initialization completed in 0.372 seconds.
Startup completed in 2.053 seconds.
Loading /home/adamsrl/.abclrc completed in 12.904 seconds.
To load "swank":
  Load 1 ASDF system:
    swank
; Loading "swank"
[package swank-loader]............................
[package swank/backend]...........................
[package swank/rpc]...............................
[package swank/match].............................
[package swank-mop]...............................
[package swank]...................................
[package swank/abcl].
; in (DEFMETHOD SOURCE-LOCATION ...)

; Caught STYLE-WARNING:
;   Undefined variable *SOURCE-PATH* assumed special

; Caught STYLE-WARNING:
;   Undefined variable *SOURCE-PATH* assumed special

...........; Compiling /home/adamsrl/.quicklisp/dists/quicklisp/software/slime-v2.23/contrib/swank-util.lisp ...
; Wrote /home/adamsrl/.slime/fasl/2.23/armedbear-1.5.0-linux-x86-64/contrib/swank-util.abcl (0.077 seconds)
; Compiling /home/adamsrl/.quicklisp/dists/quicklisp/software/slime-v2.23/contrib/swank-repl.lisp ...
..................
[package swank-repl]
;; 
;; Error compiling /home/adamsrl/.quicklisp/dists/quicklisp/software/slime-v2.23/contrib/swank-repl.lisp:
;;   The symbol "*STARTED-FROM-EMACS*" is not external in package SWANK-LOADER.
;; 
Error loading /home/adamsrl/scripts/sbcl-slime.lisp at line 2 (offset 22)
#<THREAD "interpreter" {68F1AEB}>: Debugger invoked on condition of type READER-ERROR
  The symbol "*STARTED-FROM-EMACS*" is not external in package SWANK-LOADER.
Restarts:
  0: TRY-RECOMPILING               Recompile swank-loader and try loading it again
  1: RETRY                         Retry loading FASL for #<SWANK-LOADER::SWANK-LOADER-FILE "swank" "swank-loader">.
  2: ACCEPT                        Continue, treating loading FASL for #<SWANK-LOADER::SWANK-LOADER-FILE "swank" "swank-loader"> as having been successful.
  3: RETRY                         Retry ASDF operation.
  4: CLEAR-CONFIGURATION-AND-RETRY Retry ASDF operation after resetting the configuration.
  5: ABORT                         Give up on "swank"
[1] SWANK-REPL(1): `

**Comment by stassats** [comment]
Either your slime installation or ABCL are broken.

**Comment by easye** [comment]
Mea culpa!  Fixed now.

Definitely fixed in SLIME 2.25 
https://github.com/slime/slime/commit/26a79a673a1d0ed2ee3d6346b395aa8ba084ddde

**Comment by linnilbobo** [comment]
when i use the 2.24 version on abcl, it fail and shows 

; Loading "swank"
.; Compiling /home/lin/quicklisp/dists/quicklisp/software/slime-v2.24/contrib/swank-repl.lisp ...
.................................................
[package swank-repl]
;; 
;; Error compiling /home/lin/quicklisp/dists/quicklisp/software/slime-v2.24/contrib/swank-repl.lisp:
;;   The symbol "*STARTED-FROM-EMACS*" is not external in package SWANK-LOADER.
;; 
#<THREAD "interpreter" {7A280B4E}>: Debugger invoked on condition of type READER-ERROR
  The symbol "*STARTED-FROM-EMACS*" is not external in package SWANK-LOADER.
Restarts:
  0: TRY-RECOMPILING               Recompile swank-loader and try loading it again
  1: RETRY                         Retry loading FASL for #<SWANK-LOADER::SWANK-LOADER-FILE "swank" "swank-loader">.
  2: ACCEPT                        Continue, treating loading FASL for #<SWANK-LOADER::SWANK-LOADER-FILE "swank" "swank-loader"> as having been successful.
  3: RETRY                         Retry ASDF operation.
  4: CLEAR-CONFIGURATION-AND-RETRY Retry ASDF operation after resetting the configuration.
  5: RETRY                         Retry ASDF operation.
  6: CLEAR-CONFIGURATION-AND-RETRY Retry ASDF operation after resetting the configuration.
  7: ABORT                         Give up on "swank"
  8: TOP-LEVEL                     Return to top level.
[1] SWANK-REPL(5): 

i download the newest source code on gihub and update it by 
`(push "/home/lin/abcl-bin-1.7.0/slime-master/" asdf:*central-registry*)`
it works and shows

; Compilation unit finished
;   Caught 2 STYLE-WARNING conditions
;   The following functions were used but not defined:
;     ASDF/INTERFACE::MAKE-TEMPORARY-PACKAGE
;     SWANK::KEYWORD-ARG.DEFAULT-ARG
;     SWANK::KEYWORD-ARG.ARG-NAME
;     SWANK::KEYWORD-ARG.KEYWORD
;     SWANK::OPTIONAL-ARG.DEFAULT-ARG
;     SWANK::OPTIONAL-ARG.ARG-NAME


(:SWANK)
CL-USER(6): 

https://github.com/slime/slime/issues/494#issuecomment-557914167
yes, it has fixed by new code, so please post the new version 2.25 thanks
