### ISSUE TITLE
(file-position *standard-input*) signals N-A-M

### ISSUE THREAD

**Issue by phoe** [slime/slime#620]
According to CLHS, `cl:file-position` is supposed to return a meaningful value when called on any stream, but `(file-position *standard-input*)` on slime on SBCL signals `no-applicable-method`. Should this get fixed in Swank by means of adding a nil-returning `defmethod stream-file-position` on a `slime-input-stream`, or upstream in SBCL via a default `defmethod stream-file-position` on e.g. `sb-gray:fundamental-stream`? Or in some other way?

**Comment by luismbo** [comment]
The default method seems to have been removed in SBCL 2.1.0. It seems like sb-gray should provide a default method (no idea if it's part of the gray streams quais-standard, but file-position's spec does suggest it should). Maybe ask SBCL's developers about adding such a method (I agree with https://github.com/sbcl/sbcl/commit/862ffec23f7241456c1a70c43e277b03146eed91 that the default method on t was bogus, but perhaps a default method for `sb-gray:fundamental-stream` would make sense?)

If SBCL doesn't want to add the method back, we can define something for SLIME's classes, sure.

**Comment by csrhodes** [comment]
Sorry that I didn't pick up this incompatibility and add it to NEWS at the time.

Unlike `stream-read-sequence` and `stream-write-sequence`, there isn't an obviously-correct default method for `stream-file-position`.  (The "safe" default of "do nothing" isn't obviously correct in the sense that it might well obscure the need for a correct implementation that actually provides functionality for a given stream class).

I'd prefer to move forward by putting the responsibility of the Gray Stream implementor to provide a method, in a similar way to providing a method for `stream-read-char` and friends: it's a foundational part of the protocol, rather than something that can be overridden.  Defining such a method in slime *should* be backwards-compatible with older SBCLs.

**Comment by luismbo** [comment]
Since `file-position` is specified to return `nil` (rather than an error) when the position can't be determined, it seemed like a sensible default, but I'm fine with adding the method to slime.

**Comment by phoe** [comment]
I think that @csrhodes's point is that SBCL cannot know *for sure* if the position can or can't be determined, and therefore a default method that returns `nil` might cause false negatives for situations where `file-position` actually can be meaningfully implemented in some way. (But then, I've argued with him the other way on `#sbcl` like half an hour ago ago, so I guess that I can understand both stances here.)

**Comment by luismbo** [comment]
Thanks @phoe, @csrhodes.

**Comment by phoe** [comment]
The commit fixing this is breaks CCL because it does not have a symbol named `stream-file-position` - for whatever reason, it has `stream-position` instead.

```lisp
Clozure Common Lisp Version 1.12 (v1.12) LinuxX8664

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? (apropos "stream-file-position")
? (apropos "stream-position")
CCL::*FCOMP-STREAM-POSITION*,  Value: NIL
 CCL::STREAM-POSITION, Def: STANDARD-GENERIC-FUNCTION
```

**Comment by phoe** [comment]
See the `trivial-gray-streams` workaround at https://github.com/trivial-gray-streams/trivial-gray-streams/blob/2b3823edbc78a450db4891fd2b566ca0316a7876/streams.lisp#L170-L173

```lisp
  (defmethod ccl::stream-position ((stream fundamental-stream) &optional new-position)
    (if new-position
	(setf (stream-file-position stream) new-position)
	(stream-file-position stream))))
```

**Comment by luismbo** [comment]
@phoe made this SBCL-only, thanks. I can't really test with all other Lisps at the moment.
