### ISSUE TITLE
Indexing restarts with letters

### ISSUE THREAD

**Issue by daninus14** [slime/slime#796]
When running some common lisp code and an error pops up in the REPL, sometimes there are more than 10 restart options which are indexed in the buffer that comes up. For any restart starting at 10 and beyond, pressing the "1" immediately selects the restart indexed at 1, which makes the other restarts inaccessible from the indexed key, and it only allows for placing the cursor in the option and pressing enter, or clicking with the mouse.

I would like to make the restarts indexed at >= 10 be accessible by a key short cut, either by allowing some prefix key to the number, for example `SPC 1 2`, or by indexing restarts with indices >= 10 with letters 'a' 'b' 'c' etc.

**Comment by stassats** [comment]
a and c are already used for "abort" and "continue".

**Comment by daninus14** [comment]
Thanks @stassats , the idea is just to use non reserved / available keys for the rest of the indices. 
https://slime.common-lisp.dev/doc/html/Restarts.html#Restarts
So any key can be used except for `0-9` and `a`, `c`, and `q`

**Comment by informatimago** [comment]
Well, there is a justified user interface question here.

If you dismiss an alphabetical solution as proposed (we could use uppercase letters), I would suggest to AVOID displaying integers greater than 9 for restarts, if they cannot be used!

**Comment by stassats** [comment]
The solution is to use mouse/keyboard for navigation. Not numbering restarts after some point looks pretty silly.

**Comment by informatimago** [comment]
> The solution is to use mouse/keyboard for navigation. Not numbering restarts after some point looks pretty silly.

Not all users spend a lot of time in sldb.  For them it's confusing to present the numbers above 9, since that motivates them to type 12, and get the wrong restart.  A typical cockpit error, due to the bad design of the cockpit.

It's the developer choice to not support single-key restart selection for restarts deeper than 9 (there's the keyboard navigation, so IMO there's nothing missing here, just a little inconvenient).  

But presenting the numbers from 10 up, leads users to do the wrong thing.  These numbers should be removed from display.

If the look is more important to you, you should make it consistent and efficace.  A solution could be to use the same number of digits for all restart options, ie. prefixing with 0 the small numbers.  Then we would have to type 01 for the first, and 11 for the eleventh.  No confusion possible, and nice aligned display of options with their number.
(and since we could also go over 100 or 1000, make it general and allow for 3- or 4-digit restart numbers.

If you fancy some fun, we could even invent some tree-based numbering scheme.
eg with 16 restarts, we could type 1-8 for the first eight, and 91-92 for the last eight. etc. (but the display would not be as pretty since we'd still have different length codes for the restarts).
